wandb:
  name: "jianzhirong"
  dir: "/home/levin/workspace/nerf/RoMe/outputs/"
  entity: "jianzhirong"
  tags: []
  project: "Rome"

# when on cluster, no wandb logs
cluster: False
replace_name: False

# BEV size
bev_x_length: 100
bev_y_length: 100
bev_resolution: 0.1  # meters
bev_x_pixel: 1000
bev_y_pixel: 1000
cut_range: 50

# Training Parameters
waypoint_radius: 120  # meters
batch_size: 4
pos_enc: 5
lr: 
  vertices_rgb: 0.1
  vertices_label: 0.1
  vertices_z: 0.001
  rotations: 0.01
  translations: 0.01

extrinsic:  # extrinsic optimization range
  rotation_deg: 0.5
  translation_m: 0.5
  start_epoch: 0

lr_milestones: [1, 4]
lr_gamma: 0.1
seg_loss_weight: 0.06
normal_loss_weight: 0
laplacian_loss_weight: 10
rand_seed: 17
epochs: 7

# Performance Parameters
num_workers: 8


dataset: "NerfStudio"
version: "mini" 
trip_config: "/media/levin/DATA/zf/nerf/trip_configs/vkitti_trips.config"
eval: False

# clip_list:
# - "scene-0655"

center_point:
  x: 0.0
  y: 0.0


# minimum distance between frame to sample the dataset
min_distance: 0.2

# resized image size
image_width: 1242
image_height: 375
